Remove Mosquitto 1.4.10 (fails to build)
```
Sending build context to Docker daemon 10.24 kB
Step 1/7 : FROM alpine:3.5
 ---> 8b613b705735
Step 2/7 : MAINTAINER David Audet <david.audet@ca.com>
 ---> Running in 6ea6b9cdf53b
 ---> ff52f1ca8414
Removing intermediate container 6ea6b9cdf53b
Step 3/7 : LABEL Description "Eclipse Mosquitto MQTT Broker"
 ---> Running in d13d0b52b232
 ---> 2de57e632f00
Removing intermediate container d13d0b52b232
Step 4/7 : RUN apk --no-cache add mosquitto=1.4.10-r2 &&     mkdir -p /mosquitto/config /mosquitto/data /mosquitto/log &&     cp /etc/mosquitto/mosquitto.conf /mosquitto/config &&     chown -R mosquitto:mosquitto /mosquitto
 ---> Running in 83c73d80573f
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  mosquitto-1.4.12-r0:
    breaks: world[mosquitto=1.4.10-r2]
Removing intermediate container 83c73d80573f
The command '/bin/sh -c apk --no-cache add mosquitto=1.4.10-r2 &&     mkdir -p /mosquitto/config /mosquitto/data /mosquitto/log &&     cp /etc/mosquitto/mosquitto.conf /mosquitto/config &&     chown -R mosquitto:mosquitto /mosquitto' returned a non-zero code: 1
```